---

sudo: required

services:
  - docker

env:
  - REGISTRY_URI=''

stages:
  - name: lint
  - name: test
  - name: build

jobs:
  include:
    - stage: lint
      script:
        - echo 'lint';
    - stage: test
      script: echo 'lint';
    - stage: build
      script:
        - docker build -t czeraszflaconi/node-test:latest -f ./Dockerfile .
        - docker tag czeraszflaconi/node-test:latest czeraszflaconi/node-test:${TRAVIS_COMMIT}
        - docker login --username czeraszflaconi --password $DOCKER_HUB_PASSWORD
        - docker push czeraszflaconi/node-test:latest
        - docker push czeraszflaconi/node-test:${TRAVIS_COMMIT}
